version: '3.8'

services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  mysql:
    image: mysql:latest
    container_name: mysql-coralogix
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - "3306:3306"
    volumes:
      - ./mysql-data/:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  python:
    build:
      dockerfile: Dockerfile-py
    container_name: pymain
    ports:
      - "8000:8000"
  nodejsmain:
    build:
      dockerfile: Dockerfile-mainjs
    container_name: jsmain
    ports:
    - "3000:3000"
    env_file:
      - .env
  nodejsgame:
    build:
      dockerfile: Dockerfile-game
    container_name: jsgame
    ports:
    - "3001:3001"