CREATE DATABASE coralogix
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'code'@'%' IDENTIFIED WITH caching_sha2_password BY '!root123@';
GRANT ALL PRIVILEGES ON *.* TO 'code'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;